### ISSUE TITLE
Sarah's edits links aren't being generated properly

### ISSUE THREAD

**Issue by sarah11918** [aFuzzyBear/astro-ui#45]
Links for that section are being generated under /sarahedits/ but the pages actually exist under /sarah/  (I can navigate there manually to each of the pages)

I know eventually we won't need this set at all because Sarah's edits will become THE PAGES (and then be edited to your taste), but it at least helps to have them linked and accessible for previewing. Please and thank you!

**Comment by aFuzzyBear** [comment]
Awesome, Ill take a look and get that fixed asap,

**Comment by aFuzzyBear** [comment]
That should be the proper route inplace, pushed and merged the fix buddy, 😊

**Comment by aFuzzyBear** [comment]
So I did manage to fix this, however forgot to close this issue down, 🙈 
Just doing a bit of house keeping, dont mind me =)
